import type { AnnouncementLanguageMode } from "@shared/announcements";
import { Label } from "../../../design/ui";
import { actions, type SoundPreset } from "../../../store/studyStore";
import { speechAvailable } from "../audio/announcer";
import type { Journey } from "./useJourney";

const PRESETS: Array<{ id: SoundPreset; ja: string; en: string }> = [
  { id: "train", ja: "電車の音", en: "Train only" },
  { id: "train-ann", ja: "電車＋案内", en: "Train + announcements" },
  { id: "rain", ja: "雨", en: "Rain" },
  { id: "quiet", ja: "静か", en: "Quiet" },
];

/** 音 — sound presets. Nothing plays until one of these is pressed. */
export function SoundControls({ j }: { j: Journey }) {
  const s = j.settings;
  const active = j.soundOn ? s.soundPreset : "quiet";
  return (
    <section className="snd" aria-label="Sound">
      <header className="sm-head">
        <Label en="Sound" />
        {!j.soundOn && <span className="snd-hint">Choose an option to start sound</span>}
      </header>
      <div className="sm-modes" role="radiogroup" aria-label="Sound preset">
        {PRESETS.map((p) => (
          <button
            key={p.id}
            type="button"
            role="radio"
            aria-checked={active === p.id}
            onClick={() => void j.applySoundPreset(p.id)}
          >
            <span>{p.en}</span>
            <small lang="ja">{p.ja}</small>
          </button>
        ))}
      </div>
      <div className="snd-row">
        <label htmlFor="snd-lang">
          <Label en="Announcement language" />
        </label>
        <select
          id="snd-lang"
          className="ink-select"
          value={s.announcementLanguage}
          onChange={(e) => {
            const lang = e.target.value as Exclude<AnnouncementLanguageMode, "off">;
            actions.updateSettings({
              announcementLanguage: lang,
              announcementMode:
                s.soundPreset === "train-ann" && j.soundOn ? lang : s.announcementMode,
            });
          }}
        >
          <option value="en">English</option>
          <option value="ja-en">Japanese, then English</option>
          <option value="ja">Japanese (日本語)</option>
        </select>
      </div>
      <div className="snd-row">
        <label htmlFor="snd-ann-vol">
          <Label en="Announcement volume" />
        </label>
        <input
          id="snd-ann-vol"
          type="range"
          min={0}
          max={1}
          step={0.05}
          value={s.announcementVolume}
          onChange={(e) => actions.updateSettings({ announcementVolume: Number(e.target.value) })}
        />
      </div>
      <div className="snd-row">
        <label htmlFor="snd-amb-vol">
          <Label en="Ambience volume" />
        </label>
        <input
          id="snd-amb-vol"
          type="range"
          min={0}
          max={1}
          step={0.05}
          value={s.ambientVolume}
          onChange={(e) => actions.updateSettings({ ambientVolume: Number(e.target.value) })}
        />
      </div>
      <label className="snd-check">
        <input
          type="checkbox"
          checked={s.captions}
          onChange={(e) => actions.updateSettings({ captions: e.target.checked })}
        />
        Captions for every announcement
      </label>
      <label className="snd-check">
        <input
          type="checkbox"
          checked={s.showLocalTime}
          onChange={(e) => actions.updateSettings({ showLocalTime: e.target.checked })}
        />
        Show my local time next to JST
      </label>
      {speechAvailable() && !j.jaVoice && (
        <label className="snd-check">
          <input
            type="checkbox"
            checked={s.useFallbackVoice}
            onChange={(e) => actions.updateSettings({ useFallbackVoice: e.target.checked })}
          />
          No Japanese voice installed — read Japanese with the default voice
        </label>
      )}
      <p className="snd-note">
        Announcements are generated by this site — not official railway announcements.
      </p>
    </section>
  );
}
