import { useEffect, useState } from "react";
import { Label } from "../design/ui";
import { japanApi } from "../features/japan/api";
import { PageHead } from "./PageHead";

type Status = Awaited<ReturnType<typeof japanApi.status>>["data"];

/** について — what is real, what is recorded, and where the data comes from. */
export function AboutPage() {
  const [status, setStatus] = useState<Status | null>(null);
  useEffect(() => {
    japanApi
      .status()
      .then((r) => setStatus(r.data))
      .catch(() => setStatus(null));
  }, []);
  return (
    <div className="about page-ink">
      <PageHead
        ja="について"
        en="About"
        color="var(--st-steel)"
        prev={{ ja: "旅の記録", en: "Journal" }}
      />
      <div className="about-grid">
        <section className="ink-panel ink-panel--notice">
          <h2 className="section-label">
            <Label en="What is live, what is recorded" ja="ご案内" />
          </h2>
          <dl className="about-dl">
            <dt>Times</dt>
            <dd>
              Published timetables (ODPT train timetables or GTFS / GTFS-JP). Badge: TIMETABLE.
            </dd>
            <dt>Position, delays, cancellations</dt>
            <dd>
              Real-time feeds when available (ODPT odpt:Train, GTFS-Realtime). Badge: LIVE — only
              while the data is fresh.
            </dd>
            <dt>Window view</dt>
            <dd>
              A recording embedded with permission, or an illustrated view. Never a live camera.
            </dd>
            <dt>Announcements</dt>
            <dd>
              Generated by this site (“Study Journey announcement”). Not official railway
              announcements.
            </dd>
            <dt>Demo line</dt>
            <dd>
              The Sakuraura Coast Line is fictional, for trying the site without an API key. Badge:
              DEMO.
            </dd>
            <dt>Illustrations</dt>
            <dd>
              The street and route scenes are original illustrations until licensed photography is
              added.
            </dd>
          </dl>
        </section>
        <section className="ink-panel ink-panel--board">
          <h2 className="section-label">
            <Label en="Data sources" ja="データ" />
          </h2>
          {!status && <p className="ink-empty">Server not reachable.</p>}
          <ul className="ink-list">
            {status?.providers.map((p) => (
              <li key={p.id}>
                <span>{p.label}</span>
                <span>{p.enabled ? (p.active ? "ACTIVE" : "ENABLED") : "OFF"}</span>
                <span className="muted-ink">{p.reason ?? ""}</span>
              </li>
            ))}
          </ul>
          <p className="about-small">
            Public Transportation Open Data Center (ODPT) · OpenStreetMap contributors (ODbL) ·
            YouTube IFrame Player API. Fonts: Barlow, Barlow Condensed, DotGothic16, Dela Gothic
            One, Zen Kaku Gothic New, Shippori Mincho, IBM Plex Mono (SIL OFL). Station-style design
            is inspired by Japanese railway signage; no operator marks are used.
          </p>
        </section>
      </div>
    </div>
  );
}
