import type { Station } from "./types";
import type { JourneyTimeline } from "./journey";

/**
 * Study Journey announcements — original texts generated by this app. They are not
 * operator recordings and must never be presented as official announcements.
 */

export type AnnouncementLanguageMode = "ja" | "en" | "ja-en" | "off";

export type AnnouncementKind =
  "pre-departure" | "departed" | "approaching" | "arrival" | "delay" | "cancelled";

export interface AnnouncementEvent {
  /** stable id, used for de-duplication across re-renders and reloads */
  id: string;
  kind: AnnouncementKind;
  at: number; // ms
  stationId: string;
  textJa: string;
  textEn: string;
}

export const ANNOUNCEMENT_LABEL = "Study Journey announcement";

export interface AnnouncementTiming {
  preDepartureSeconds: number;
  afterDepartureSeconds: number;
  approachingSeconds: number;
}

export const DEFAULT_TIMING: AnnouncementTiming = {
  preDepartureSeconds: 60,
  afterDepartureSeconds: 20,
  approachingSeconds: 50,
};

export const templates = {
  departureJa: (station: Station, next?: Station) =>
    `まもなく、${station.nameJa}を発車いたします。` + (next ? `次は、${next.nameJa}です。` : ""),
  departureEn: (station: Station, next?: Station) =>
    `We will soon depart from ${station.nameEn}.` +
    (next ? ` The next station is ${next.nameEn}.` : ""),
  departedJa: (next: Station, terminal: Station) =>
    `本日もご利用いただきありがとうございます。この電車は${terminal.nameJa}行きです。次は、${next.nameJa}です。`,
  departedEn: (next: Station, terminal: Station) =>
    `This train is bound for ${terminal.nameEn}. The next station is ${next.nameEn}.`,
  approachingJa: (station: Station) =>
    `まもなく、${station.nameJa}です。お忘れ物のないようご注意ください。`,
  approachingEn: (station: Station, next?: Station) =>
    `We will soon arrive at ${station.nameEn}.` +
    (next
      ? ` The stop after ${station.nameEn} is ${next.nameEn}.`
      : " This is the last stop of your journey."),
  arrivalJa: (station: Station, final: boolean) =>
    final
      ? `${station.nameJa}、${station.nameJa}です。お疲れさまでした。`
      : `${station.nameJa}、${station.nameJa}です。`,
  arrivalEn: (station: Station, final: boolean) =>
    final
      ? `${station.nameEn}. This is the end of your study journey. Well done.`
      : `${station.nameEn}.`,
  delayJa: (minutes: number) => `この電車は、ただいま約${minutes}分遅れて運転しております。`,
  delayEn: (minutes: number) =>
    `This train is currently delayed by approximately ${minutes} minute${minutes === 1 ? "" : "s"}.`,
  cancelledJa: () => `この電車は運休となりました。ご迷惑をおかけしております。`,
  cancelledEn: () => `This train service has been cancelled.`,
};

/**
 * Builds the announcement schedule for a journey from its (estimated) timeline.
 * Event ids depend only on trip + station + kind, so re-building after a delay update
 * never causes repeats; delay events include the delay bucket so a *change* is announced.
 */
export function buildAnnouncementEvents(
  timeline: JourneyTimeline,
  stations: Map<string, Station>,
  timing: AnnouncementTiming = DEFAULT_TIMING,
): AnnouncementEvent[] {
  const events: AnnouncementEvent[] = [];
  const stops = timeline.stops;
  const st = (id: string): Station => stations.get(id) ?? { id, nameJa: id, nameEn: id };
  const terminal = st(stops[stops.length - 1].stationId);
  const key = (stationId: string, kind: string) => `${timeline.tripId}:${stationId}:${kind}`;

  stops.forEach((stop, i) => {
    const here = st(stop.stationId);
    const next = stops[i + 1] ? st(stops[i + 1].stationId) : undefined;
    const isFirst = i === 0;
    const isLast = i === stops.length - 1;

    if (!isFirst) {
      const prevDep = stops[i - 1].estimatedDeparture;
      const approachAt = Math.max(
        stop.estimatedArrival - timing.approachingSeconds * 1000,
        prevDep + (timing.afterDepartureSeconds + 10) * 1000,
      );
      if (approachAt < stop.estimatedArrival) {
        events.push({
          id: key(stop.stationId, "approaching"),
          kind: "approaching",
          at: approachAt,
          stationId: stop.stationId,
          textJa: templates.approachingJa(here),
          textEn: templates.approachingEn(here, next),
        });
      }
      events.push({
        id: key(stop.stationId, "arrival"),
        kind: "arrival",
        at: stop.estimatedArrival,
        stationId: stop.stationId,
        textJa: templates.arrivalJa(here, isLast),
        textEn: templates.arrivalEn(here, isLast),
      });
    }
    if (!isLast) {
      const dwell = stop.estimatedDeparture - stop.estimatedArrival;
      const preLead = isFirst ? timing.preDepartureSeconds * 1000 : Math.min(dwell, 15_000);
      if (isFirst || dwell >= 10_000) {
        events.push({
          id: key(stop.stationId, "pre-departure"),
          kind: "pre-departure",
          at: stop.estimatedDeparture - preLead,
          stationId: stop.stationId,
          textJa: templates.departureJa(here, next),
          textEn: templates.departureEn(here, next),
        });
      }
      const segment = stops[i + 1].estimatedArrival - stop.estimatedDeparture;
      if (isFirst || segment >= 90_000) {
        events.push({
          id: key(stop.stationId, "departed"),
          kind: "departed",
          at: stop.estimatedDeparture + timing.afterDepartureSeconds * 1000,
          stationId: stop.stationId,
          textJa: templates.departedJa(next!, terminal),
          textEn: templates.departedEn(next!, terminal),
        });
      }
    }
  });
  return events.sort((a, b) => a.at - b.at);
}

/** Event announcing a meaningful (≥ 2 min) delay or a cancellation, created at `now`. */
export function statusChangeEvent(
  timeline: JourneyTimeline,
  now: number,
): AnnouncementEvent | null {
  if (timeline.cancelled) {
    return {
      id: `${timeline.tripId}:status:cancelled`,
      kind: "cancelled",
      at: now,
      stationId: "",
      textJa: templates.cancelledJa(),
      textEn: templates.cancelledEn(),
    };
  }
  const minutes = Math.round(timeline.delaySeconds / 60);
  if (minutes < 2) return null;
  return {
    id: `${timeline.tripId}:status:delay-${minutes}`,
    kind: "delay",
    at: now,
    stationId: "",
    textJa: templates.delayJa(minutes),
    textEn: templates.delayEn(minutes),
  };
}

/**
 * Events that should play now: due, not yet played, and not older than `maxLateSeconds`
 * (so joining mid-journey or returning to a background tab does not replay a backlog).
 */
export function dueAnnouncements(
  events: AnnouncementEvent[],
  now: number,
  played: ReadonlySet<string>,
  maxLateSeconds = 20,
): AnnouncementEvent[] {
  return events.filter(
    (e) => !played.has(e.id) && e.at <= now && now - e.at <= maxLateSeconds * 1000,
  );
}

/** Ids of events that were missed (too late) — mark them as handled without playing. */
export function missedAnnouncements(
  events: AnnouncementEvent[],
  now: number,
  played: ReadonlySet<string>,
  maxLateSeconds = 20,
): string[] {
  return events
    .filter((e) => !played.has(e.id) && now - e.at > maxLateSeconds * 1000)
    .map((e) => e.id);
}

export function announcementTexts(
  e: AnnouncementEvent,
  mode: AnnouncementLanguageMode,
): Array<{ lang: "ja-JP" | "en-US"; text: string }> {
  switch (mode) {
    case "off":
      return [];
    case "ja":
      return [{ lang: "ja-JP", text: e.textJa }];
    case "en":
      return [{ lang: "en-US", text: e.textEn }];
    case "ja-en":
      return [
        { lang: "ja-JP", text: e.textJa },
        { lang: "en-US", text: e.textEn },
      ];
  }
}
